# specifies path where to save models and logs
experiment_path: experiment_densenet121_weighted

# model config
model:
  name: classifier
  backbone: densenet121
  num_classes: 2
  head: simple

# datasets
img_size: 384
train:
  name: mura_dataset
  data_path: /home/vasyl/work/tmp/MURA-v1.1/train_image_paths.csv
  img_size: 384
  prefix: /home/vasyl/work/tmp
val:
  name: mura_dataset
  data_path: /home/vasyl/work/tmp/MURA-v1.1/valid_image_paths.csv
  img_size: 384
  prefix: /home/vasyl/work/tmp

# loss function
loss:
  name: cross_entropy
  weights: [0.4, 0.6]

# optimizer and scheduler configs
optimizer:
  lr: 0.0001
scheduler:
  metric_to_monitor: val/accuracy
  metric_mode: max
  patience: 5
  factor: 0.5
  min_lr: 0.000001

# checkpoint callback
metric_to_monitor: val/accuracy
metric_mode: max

# trainer
gpus: [0, 1]
min_epochs: 10
max_epochs: 80
progress_bar_refresh_rate: 1
batch_size: 8
